import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GraphProvider from "@/providers/graph";
import "./globals.css";
import { Layout, Nav, Main } from "./_components/Layout";
import Panel from "./_components/Panel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Root = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GraphProvider>
          <Layout>
            <Nav>
              <Panel />
            </Nav>
            <Main>{children}</Main>
          </Layout>
        </GraphProvider>
      </body>
    </html>
  );
};

export default Root;
